### ISSUE TITLE
Compatibility with ARC9 Polyarms Project

### ISSUE THREAD

**Issue by highblaz97** [AerosunST/the_villain_arc9_unlameifier#3]
Hi, just my request and suggestion. Could you make this addon compatible with the Polyarms pack? The Polyarms guns lack some scopes, tacticals, and grips etc. Maybe you can make the unlameifier able to use these with this pack. Tq.

**Comment by AerosunST** [comment]
This is planned. Not my focus right now though.

**Comment by AerosunST** [comment]
Hi! You can now use attachments on PolyArms thanks to the new Unlameifier Core update. Have fun :)
