### ISSUE TITLE
eft optic slots, laser slots, etc on slots like back up sights and other slots?

### ISSUE THREAD

**Issue by FEXlol** [AerosunST/the_villain_arc9_unlameifier#4]
[basically something like this](https://hub.sp-tarkov.com/files/file/790-allthebackupsights/)
dont know if you are allowed to suggest stuff here but ill try my luck

this is technically possible by putting a cod converter and putting a tarkov converter ontop of it, but this doesn't work for other slots like top tactical. nor will it allow lasers to be put on

**Comment by AerosunST** [comment]
Should be able to do this now with the latest version. Have fun :)
