### ISSUE TITLE
GSR Support?

### ISSUE THREAD

**Issue by Mememan97GithubEdition** [AerosunST/the_villain_arc9_unlameifier#6]
being restricted to only optics and stocks feels limiting, maybe allow muzzle attachments and tacticals too?

**Comment by AerosunST** [comment]
This will be added as part of the cross-compatibility rewrite. Current focus is the tuning system.

**Comment by AerosunST** [comment]
Hi, me again. In the process of adding content to the new Unlameifier Core (previously referred to as the Cross-Compatibility rewrite). You are now able to do this using EFT attachments at the current moment. GSR, MW19, CoD Pack, and more will be added in the future.
